### ISSUE TITLE
Slave EVSE not returning to normal mode after Solar mode was active

### ISSUE THREAD

**Issue by djoenez** [serkri/SmartEVSE-3#122]
My skoda does not want to play nice with solar mode if there are alot of clouds (so the charging gets started and stopped a couple of times) So i just want to put it in normal mode but a low charging current to fix this during cloudy days.

unfortunately when i had both my chargers on solar, switch master to Off (only want to charge my slave) and switch slave to normal i  still have the status: Waiting for solar. and if reboot the EVSE, it will default to solar again.

**Comment by dingo35** [comment]
Could you post the settings of both EVSEs?

**Comment by dingo35** [comment]
What happens if you put both on Solar, switch Slave to Normal, and then switch Master to Off?

**Comment by djoenez** [comment]
Hello Dingo, will do asap, unfortunately i will not be home with 2 cars for the next two weeks, will update ASAP (thanks for looking into this!).

Just a question for my understanding: Is it possible to use the EVSE2 (smart or solar) when master is in off mode? or is this prohibited? 

Maybe also a feature request: I ask these questions because sometimes i have two cars connected but i want to charge one car in particular of solar (and only start charging the second car when i have enough solar power, i have enough to charge 1x16A + 1x8A for example). But now i don't have this choice, is there a way to "toggle" the preferred car? Or when the car is connected to have a toggle which states you may charge (so you prevent it to charge even when the selected mode is solar?)

**Comment by dingo35** [comment]
The "OFF"mode is actually setting the Access bit off; so this is the same as when you have RFID reader activated and you would not identify yourself with a valid RFID card.

So I would expect the original firmware to be able to charge on EVSE2 when EVSE1 is not used/no RFID card is presented; and I would expect the serkri firmware to do the same, since we did not (intentionally) change that behaviour.

But I only have 1 EVSE so I cannot test it for you....

I understand your feature request, makes a lot of sense; for the near future I would use HomeAssistant and the ha-smartevse integration to script this kind of behaviour. I intend to start using solar mode this summer (also through HomeAssistant) and when I have some practical experience I might either publish my HA automations OR build them into the SmartEVSE firmware....

**Comment by dingo35** [comment]
@djoenez could you please test this with newest release 1.6.0 and, if problem still exists, post the verbose telnet/debug log here?

**Comment by djoenez** [comment]
@dingo35, will do. Just got back from long work related travel, as soon as i use the second car again i will update this thread with testing. Thanks!

**Comment by djoenez** [comment]
Works now as expected. Thanks for the fix!
