### ISSUE TITLE
Non persistant mode after reboot/reconect 

### ISSUE THREAD

**Issue by stevoh6** [serkri/SmartEVSE-3#169]
Hi, Im using new 1.7.0 version and Im facing problem, when evse is reboot or rejoin wifi with mode persistance. 

When I set mode to OFF, then reboot ( or wifi is reconected), mode is changed to NORMAL. this is unwanted scenario, because today at night my home solar battery discharge to 0 because or this.

The original behaviour was, that mode is persistant during reboots.  Can you please bring it back? Its bug? or feature?

**Comment by stevoh6** [comment]
I found the issue, automations in example was wrong. 
Tested, this should help
https://github.com/serkri/SmartEVSE-3/compare/master...stevoh6:SmartEVSE-3:patch-1

**Comment by dingo35** [comment]
I think your patch only solves part of the problem; I only use MQTT to read out my sensors, and I lost persistence of mode after reboot too.... I'm working on a patch, retaining mode is simple, but somehow retaining the access_bit (OFF vs. ON) has never worked and is not simple to store.....

**Comment by dingo35** [comment]
[persistence.zip](https://github.com/serkri/SmartEVSE-3/files/12039327/persistence.zip)
Could you test this; especially with your MQTT config, interesting to see if it interferes.

Thx!

**Comment by dingo35** [comment]
@arpiecodes  you actually (accidentally, I presume) removed the code that was saving the mode in NVP; I reinstated it so now it is saved whenever mode / access bit is changed, either by MQTT, API or webserver.

Should be fixed by fce52a2f44e36a449b88ffdaa8d66099f9abac3e.

On the capitalisation of Mode OFF, I don't get your point; why is that a bug, does it matter other than optics, is something depending on its spelling?

**Comment by stevoh6** [comment]
OI can test it after weekend. Yes, my problem was caused by MQTT, that smartevse read set mode parameter (( which wasnt properly updated), my fix fixed that part in HA automation example, now its forking for me just fine :-)
