### ISSUE TITLE
Communication Error

### ISSUE THREAD

**Issue by deqw** [serkri/SmartEVSE-3#22]
So now and then I get a Communication Error in my response: "error":"Communication Error","error_id":2

What exactly is this error (caused by)? Can this error be assigned to a specific address on the RS485 bus?

Thanks.

**Comment by fluppie** [comment]
I sometimes have it when switching from solar to smart/normal, for some reason it puts the Sensorbox as active mains meter instead of the Aastron meter. Maybe it's a bug when switching between off/solar/smart etc?

**Comment by deqw** [comment]
No switching at all in my case. It happens also when the SmartEVSE is idle for days. I'm checking the status every minute and get an email when the status changes. So I see the status changing from Good to Error and vv for a few times in a row and then for days the status is Good. Of course when charging the charge will be interrupted. I'm using two Eastron SDM630 V2, one for mains and one for EVSE. So I like more specifics for this error, eg. can it be assigned to a bus address. The bus is terminated on both sides with 120 Ohm, according to Eastron documentation (but without termination I see the same).

**Comment by k-janssens** [comment]
This is part of the original code so beside the current info, I won't be able to give some more light on this issue.

Now in general what I tend to do is to have a certain threshold for when an error happens.
So it needs to be in error for X minutes before it really is an error as it could be a short fluke and the system is able to recover from it itself
Mainly because I use home assistant and it is not uncommon there is a short comm error happening with the 100+ devices it is interacting with.

**Comment by deqw** [comment]
I'm using Home Assistant/Node Red for polling etc. Although the error itself is not that important and it always recovers, an error will interrupt charging, so a threshold will not do in that situation. I'd rather solve the problem. Thanks anyway for your reaction.

**Comment by rvdgaag** [comment]
Your polling causes collisions since the smartens acts as a master and your home-assistant too. Change the polling frequency to once a minute and you're fine. Smartevse by the way polls every 2 seconds and when there is a collision it holds for 5 seconds, when to many collisions occur the relay switches off.

**Comment by deqw** [comment]
The polling is over wifi/http, so I don’t see a problem for a busy bus there. Polling interval was once per 5 minutes and once per minute now to have more accurate sense of the duration of the error. The polling was actually to check WiFi, but then this bus error popped up from the http response.

**Comment by k-janssens** [comment]
This error normally indicates a problem with modbus comms, so it has nothing to do with the Wifi conn or the HTTP comm.
As said, this is part of the original code, the API just returns the information.

**Comment by koen-serneels** [comment]
Another option is to create a second modbus for power metering and use a cheap modbus/tcp master like this one https://www.waveshare.com/wiki/RS485_TO_ETH_(B). I'm working on a configurable modbus prometheus exporter so that these values can easily be scraped from multiple sources

**Comment by deqw** [comment]
Haven't got any Communication Error since some time now. Still running @dingo35 'Version: 09:58:33 @Jul 8 2022' at the moment.

**Comment by dingo35** [comment]
Thanks for testing @deqw ; IMHO this issue should only be closed when #40 is committed.
