### ISSUE TITLE
EVCC.io support

### ISSUE THREAD

**Issue by fluppie** [serkri/SmartEVSE-3#33]
Pretty cool software, plug-in for Home Assistant is available
https://docs.evcc.io/docs/Home

Don't know if hard to support :)

**Comment by dingo35** [comment]
Why would you use yet another piece of software, if you can interface directly with Home Assistant via the REST API:

`sensor:
  - platform: rest
    resource: http://SmartEVSE-51446.lan/settings
    name: smartevse
    scan_interval: 300
    timeout: 20
    json_attributes:
      - mode
#      - mode_id
      - car_connected
      - evse
      - settings
      - ev_meter
      - mains_meter
      - phase_currents
    value_template: "OK"

`

**Comment by dingo35** [comment]
You can do all that in Homeassistant. I have an automation that charges up until a nr of kms or % of range it reaches, because my vehicle doesn't support it (reliably). And you can pit any timer on it you want.

And it can _never_ communicate in more detail with the vehicle itself than SmartEVSE, since it has to get the data either from the EVSE or from the API of the manufacturer.

It positions itself as a  information broker, just like Homeassistant. But Homeassistant has a much bigger user base and much more interfaces to other components. 

But if you like it, build an interface and put it in a PR....

fluppie ***@***.***> schreef op 9 juli 2022 20:27:37 CEST:
