### ISSUE TITLE
Understanding API

### ISSUE THREAD

**Issue by rvdgaag** [serkri/SmartEVSE-3#57]
Trying to use the API with http commands i try to change the mode of the EVSE with http://192.168.1.18/settings?mode=3

What am I doing wrong ? It show just the settings screen like http://192.168.1.18/settings 

Am I a noob ?

**Comment by koen-serneels** [comment]
I'm assuming you're testing via a browser? The settings endpoint is a http post (see https://swagger-ui.serkri.be/#/Operations/updateSettings), so you need something that can http post data instead of http get (which is what happens if you enter a url in the address bar of your browser), for example using postman or curl.

Curl example: `curl -v -X POST http://ip/settings?mode=0`
